name: Coverage

on:
  push:
    branches:
      - main
      - dev

jobs:
  coverage:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=22.11.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm test:unit:coverage

      - name: Extract coverage percentage and update README badge
        run: |
          COVERAGE_COLOR=""
          PCT=$(jq '.total.lines.pct' ./coverage/coverage-summary.json)

          if (( $(echo "$PCT < 50" | bc -l) )); then
              COVERAGE_COLOR="red"
          elif (( $(echo "$PCT < 80" | bc -l) )); then
              COVERAGE_COLOR="yellow"
          else
              COVERAGE_COLOR="brightgreen"
          fi

          COVERAGE_BADGE="https://img.shields.io/badge/coverage-${PCT}%25-${COVERAGE_COLOR}.svg"
          sed -i "s|https://img.shields.io/badge/coverage-[^)]*|${COVERAGE_BADGE}|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update coverage badge"
          git push